baseurl="/"
MetaDataFormat="json"
title="Reebok"
languageCode="en-us"
disablePathToLower="true"

[params]
CopyrightHTML="Copyright &#xA9; 2016 TvPage. All Rights Reserved."
loginId = "1758151"
subfolder = ""
hostdomain = "www.goodlookingbean.com"
description="The Good Looking Bean, did you want a coffee?"